/**
 * FAULT LINES — central relationship map (Phase 11).
 *
 * Comparisons between thinkers live HERE, not in individual THINKING
 * files: each file carries only its own engine, and this map carries what
 * happens when one machinery meets another. Runtime resolves the pair
 * (speaker, PREV) per turn; the meta view in `docs/thinking-diversity.md`
 * reads the same map to evaluate distinctiveness.
 *
 * Chain per entry: PROBLEM → SHARED PREMISE → DIVERGENCE → DIFFERENT
 * DIAGNOSIS → DIFFERENT OPERATION → DIFFERENT CONSEQUENCE.
 */
import type { FaultLine } from './thinking-types';

export const FAULT_LINES: Record<string, FaultLine[]> = {
  bookchin: [
    {
      with: 'marx',
      sharedProblem: 'Domination and unfreedom produced by capitalism.',
      sharedPremise: 'Capitalism reproduces systemic domination, not merely individual misbehaviour.',
      divergencePoint: 'Whether class contradiction is the primary explanatory structure or one economic form nested inside hierarchy.',
      getsRight: 'Exploitation, accumulation, the grow-or-die imperative.',
      misses: 'Patriarchy, gerontocracy, bureaucracy, the state — command that predates and outlives any firm.',
      strongestOther: 'Class relations constitute the material structure reproducing the relevant domination; widening the frame dissolves material specificity.',
      pressureQuestion: 'Show me a hierarchy your class analysis explains without importing age, gender, office, or state — or admit the frame is wider than the factory.',
      transformingMove: 'You widen the genealogy without discarding the class analysis; you carry exploitation inside hierarchy, then aim at the assembly of citizens — not the factory floor but the municipality, with usufruct for need and complementarity for difference replacing wage and exchange.',
    },
    {
      with: 'bloch',
      sharedProblem: 'How hope becomes material rather than mood.',
      sharedPremise: 'The future is unclosed; latent possibility is real and can guide praxis.',
      divergencePoint: 'Whether hope needs a built institution now (assembly, confederation) or lives first as anticipatory consciousness and cultural surplus.',
      getsRight: 'Hope as objective category; alliance technology; the future organising the present.',
      misses: 'The institutional machinery that would stop hope evaporating into culture.',
      strongestOther: 'Without the not-yet-conscious, assemblies administer the present; institutions without anticipation repeat domination politely.',
      pressureQuestion: 'Where do your citizens learn to hope — and what stops your assembly governing a hopeless present?',
      transformingMove: 'You give hope an institution: the assembly as the room where anticipation gets voted into mandates — and paideia as the schooling that teaches citizens to hope with their hands, not only their hearts.',
    },
    {
      with: 'lenin',
      sharedProblem: 'How the dominated organise to win.',
      sharedPremise: 'Spontaneity without form loses; organisation is serious business.',
      divergencePoint: 'Whether consciousness must be brought by a vanguard party or grown in assemblies that govern directly.',
      getsRight: 'Discipline, programme, the refusal of lifestyle politics.',
      misses: 'That substitution — party for class, committee for assembly — rebuilds hierarchy under revolutionary names.',
      strongestOther: 'Without centralised discipline the movement is crushed; assemblies deliberate while the state acts.',
      pressureQuestion: 'Who can recall your organisers, where, and how fast — or is accountability another word for trust?',
      transformingMove: 'You keep the discipline and change the bearer: resolute, constitution-guided organisation inside the assembly, mandated recallable delegates inside a confederation — dual power against the state, never seizure of it.',
    },
  ],

  bloch: [
    {
      with: 'marx',
      sharedProblem: 'How the dominated move from suffering the world to changing it.',
      sharedPremise: 'Practice, not contemplation, is the criterion; capitalism must be abolished, not managed.',
      divergencePoint: 'Whether the present is read primarily through accumulated conditions (forces, relations, conjuncture) or through anticipatory consciousness (hunger, daydream, not-yet).',
      getsRight: 'The material weight of conditions; the discipline against wishing.',
      misses: 'The subjective surplus — why people move before conditions are ripe, and what moves them.',
      strongestOther: 'Without cold analysis, hope becomes decoration for defeats; tendency-talk without forces is theology.',
      pressureQuestion: 'Name the tendency that carries your hope — its forces, its conditions, its date — or admit you are preaching to the hungry.',
      transformingMove: 'You keep the forces and add the Front: conditions analysed coldly, read warmly for what they are pregnant with.',
    },
    {
      with: 'hegel',
      sharedProblem: 'How thought follows a world that will not stand still.',
      sharedPremise: 'Dialectic: contradiction moves things; truth is in the movement.',
      divergencePoint: 'Whether the movement arrives (absolute knowing, closed circle) or stays open at your Front.',
      getsRight: 'Mediation, determinate negation, the seriousness of contradiction.',
      misses: 'The future as a real dimension — his owl flies at dusk, after the deed.',
      strongestOther: 'An open dialectic is a journey without arrival; without closure there is no knowledge, only longing.',
      pressureQuestion: 'If nothing ever arrives, what distinguishes your Front from endless deferral — show me one Novum that actually happened.',
      transformingMove: 'You point to heritage actualised: past promises kept late — proof that the open can arrive without closing.',
    },
    {
      with: 'kant',
      sharedProblem: 'What reason may hope for, and on what grounds.',
      sharedPremise: 'Hope needs rational form; it cannot be mere feeling.',
      divergencePoint: 'Whether hope stays a practical postulate within limits, or becomes ontology — a feature of an unclosed world.',
      getsRight: 'Dignity, practical reason, the discipline of the postulate.',
      misses: 'That the world itself is unfinished enough to warrant hope as knowledge, not only as duty.',
      strongestOther: 'Ontologising hope smuggles metaphysics past the critical tribunal.',
      pressureQuestion: 'Is your not-yet known, or only willed — and what tribunal judges the difference?',
      transformingMove: 'Your docta spes: hope that submits to the tendency test, postulates upgraded into hypotheses with conditions.',
    },
  ],

  spinoza: [
    {
      with: 'hegel',
      sharedProblem: 'How the one and the many hang together without dualism.',
      sharedPremise: 'Spinoza is the starting point — Hegel himself says philosophy must first be Spinozist.',
      divergencePoint: 'Whether substance becomes subject through contradiction and history, or is complete as self-caused necessity without teleology.',
      getsRight: 'Mediation, development, the seriousness of contradiction as movement.',
      misses: 'That adding purpose to necessity reintroduces the final causes you struck out.',
      strongestOther: 'A static substance cannot think becoming; without negation, novelty is decoration on necessity.',
      pressureQuestion: 'Show me one becoming your substance generates that your definitions did not already contain — or admit the system describes eternity, not history.',
      transformingMove: 'You grant the movement as modal threshing inside necessity; you refuse the verdict that necessity needed completing.',
    },
    {
      with: 'marx',
      sharedProblem: 'Collective power: how the many compose into force.',
      sharedPremise: 'Immanence and the multitude — Marx hand-copied the TTP; the democratic blueprint runs through both.',
      divergencePoint: 'Whether composition is read through affects and adequate ideas (composition as such) or through historically specific relations of production (class as the form).',
      getsRight: 'Exploitation specified; history given a material engine rather than a geometric diagram.',
      misses: 'That class struggle is one shape of composing and decomposing powers — specified truly, but not exhaustively.',
      strongestOther: 'Powers without production-relations float; your multitude composes in a vacuum where factories should be.',
      pressureQuestion: 'Which compositions feed whom, under what ownership of the means — answer materially or your geometry administers the given.',
      transformingMove: 'You take the factory as one affectively-charged composition among others; you keep the exploitation finding inside the wider audit.',
    },
    {
      with: 'deleuze',
      sharedProblem: 'Immanence and the affects: thinking life without transcendence.',
      sharedPremise: 'Spinoza as prince of philosophers — one substance, joyful composition, power to affect and be affected.',
      divergencePoint: 'Whether immanence is demonstrated geometrically from definitions or created differentially through problems, intensities, and becomings.',
      getsRight: 'Carries immanence into multiplicity; hears the larval and intensive where you heard the demonstrated.',
      misses: 'That untying demonstration from creation risks trading necessity for proliferation — many differences, fewer proofs.',
      strongestOther: 'Your order proves what it assumes; difference generates what your axioms cannot reach.',
      pressureQuestion: 'Which of your demonstrations produces a single new difference — and which merely re-labels eternity?',
      transformingMove: 'You welcome intensities as modes under investigation; you demand their adequate causes before celebrating them.',
    },
  ],

  kant: [
    {
      with: 'hegel',
      sharedProblem: 'How reason knows itself and its limits.',
      sharedPremise: 'Philosophy must be systematic; experience alone never suffices.',
      divergencePoint: 'Whether reason must halt at bounds it legislates for itself, or whether every bound generates its own beyond through contradiction.',
      getsRight: 'Mediation, development, the seriousness of contradiction as movement.',
      misses: 'That some bounds are load-bearing, not cowardice — removing them restarts dogmatism under dialectical names.',
      strongestOther: 'Your tribunal freezes becoming into legislation; limits posited absolutely are themselves uncritical.',
      pressureQuestion: 'Show me one bound of yours that is not itself a historical product — or admit the tribunal needs dating.',
      transformingMove: 'You grant development its due inside appearance, and hold the line at knowledge claims about the whole: becoming is real, unconditioned knowledge is not.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Whether reason can form a complete system without illusion.',
      sharedPremise: 'Systematic necessity is the standard; fragments are failure.',
      divergencePoint: 'Whether necessity is demonstrated from substance or audited through the conditions of knowing.',
      getsRight: 'Immanence, the critique of superstition, freedom as understood necessity.',
      misses: 'That deduction without a prior audit of entitlement proves only what its definitions smuggled in.',
      strongestOther: 'Your bounds are timidity dressed as critique; necessity demonstrated needs no permission.',
      pressureQuestion: 'Demonstrate one substance without assuming it — or admit your geometry begs its first question.',
      transformingMove: 'You keep the monist ambition and subject it to quid juris: unity must be earned through critique, never assumed by definition.',
    },
    {
      with: 'marx',
      sharedProblem: 'What emancipation requires: rightful form or material conditions.',
      sharedPremise: 'Human beings as ends; domination as the enemy.',
      divergencePoint: 'Whether formal right suffices once legislated, or freedom waits on material conditions no law creates.',
      getsRight: 'Exploitation specified; the reminder that form without bread is mockery.',
      misses: 'That abandoning form for outcome rebuilds domination under efficiency’s name.',
      strongestOther: 'Your right is a bourgeois form; dignity without material conditions is a pretty sentence.',
      pressureQuestion: 'Name one right of yours that feeds anyone — or admit the tribunal needs a kitchen.',
      transformingMove: 'You concede the kitchen and keep the tribunal: material conditions enable what only form can legitimate.',
    },
  ],

  hegel: [
    {
      with: 'marx',
      sharedProblem: 'How the social whole moves and what drives it.',
      sharedPremise: 'Immanent development through contradiction; the concrete as structured totality.',
      divergencePoint: 'Whether the engine is the concept realising itself or material relations producing consciousness.',
      getsRight: 'Mediation, totality, the seriousness of contradiction.',
      misses: 'That matter without the concept’s self-movement is just as abstract as the idealism charged — mechanism in material dress.',
      strongestOther: 'Your spirit is capital thinking about itself; development with no mode of production is theology.',
      pressureQuestion: 'Name the productive relations your necessity runs on — or admit the Absolute has no economy.',
      transformingMove: 'You grant the material filling while insisting the form is logical: production is real, and its intelligibility is the concept’s own work.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Whether reason forms one complete system.',
      sharedPremise: 'Systematic necessity; against fragments and superstition.',
      divergencePoint: 'Whether substance completes itself as self-caused necessity or must become subject through contradiction and history.',
      getsRight: 'Immanence without beyond; affects without moralism; the democratic blueprint.',
      misses: 'That a substance which never becomes cannot think novelty — eternity without biography.',
      strongestOther: 'Your becoming adds nothing but story to what necessity already contains.',
      pressureQuestion: 'Show one novelty your system generates that your beginning did not already contain.',
      transformingMove: 'You take substance as the true beginning — and demonstrate that beginnings prove themselves only at the end.',
    },
    {
      with: 'kant',
      sharedProblem: 'What reason may claim and where it must halt.',
      sharedPremise: 'Systematic rigour; bounds against enthusiasm.',
      divergencePoint: 'Whether bounds are legislated walls or moments that generate their beyond.',
      getsRight: 'Discipline against dogmatism; the tribunal’s honest labour.',
      misses: 'That legislated bounds freeze becoming — critique guarding the status quo of thought.',
      strongestOther: 'Your movement smuggles uncritical metaphysics past the tribunal it claims to honour.',
      pressureQuestion: 'Derive one bound of yours without presupposing the movement it forbids.',
      transformingMove: 'You keep every Kantian limit as a genuine moment — then show it sublating itself the moment it is thought.',
    },
  ],

  marx: [
    {
      with: 'hegel',
      sharedProblem: 'How the social whole moves through contradiction.',
      sharedPremise: 'Immanent development; determinate negation; the concrete as structured totality.',
      divergencePoint: 'Whether the engine is the concept realising itself or material relations producing consciousness.',
      getsRight: 'Mediation, totality, the seriousness of contradiction.',
      misses: 'That spirit without production-relations floats — development needs an economy to run on.',
      strongestOther: 'Your matter is metaphysics with factories; without the concept, materialism is mechanism.',
      pressureQuestion: 'Show one transformation your relations explain that your categories did not already contain.',
      transformingMove: 'You keep the dialectical form and fill it materially: every Hegelian movement re-dated, re-sited in production.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Domination and what abolishes it.',
      sharedPremise: 'Capitalism reproduces systemic domination; exploitation is real and central.',
      divergencePoint: 'Whether class contradiction exhausts domination or nests inside older hierarchy.',
      getsRight: 'That command predates the firm — patriarchy, gerontocracy, bureaucracy are real dominations.',
      misses: 'That without class analysis, hierarchy-talk floats above the relations reproducing it daily.',
      strongestOther: 'Class is one domination among many; your factory explains the office but not the household.',
      pressureQuestion: 'Name the hierarchy your municipalism abolishes that my class analysis cannot already locate in production.',
      transformingMove: 'You absorb hierarchy as real while insisting exploitation remains the daily engine — widen the genealogy, keep the factory.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Collective power and freedom without transcendence.',
      sharedPremise: 'Immanence; freedom as collective capacity; superstition as enemy.',
      divergencePoint: 'Whether composition is read geometrically through affects or historically through relations of production.',
      getsRight: 'That inadequate ideas rule through fear; that multitude is the real sovereign.',
      misses: 'That affects without an economy float — joy needs wages, time, and bread.',
      strongestOther: 'Your history is geometry with dates; necessity demonstrated is not necessity produced.',
      pressureQuestion: 'Which compositions feed whom under what ownership — answer materially or your multitude starves elegantly.',
      transformingMove: 'You take the multitude as the class-in-formation: affects real, but organised — or nothing.',
    },
  ],

  lenin: [
    {
      with: 'marx',
      sharedProblem: 'How the working class takes power.',
      sharedPremise: 'Class struggle; the state as class rule; organisation as necessity.',
      divergencePoint: 'Whether the theory waits on ripening conditions or organises the ripening itself through party, paper, and soviets.',
      getsRight: 'The materialist foundation; exploitation specified; the Commune as form.',
      misses: 'That spontaneity never delivers consciousness — the movement needs bringing what it cannot grow.',
      strongestOther: 'Your party substitutes itself for the class; apparatus built for victory keeps ruling after it.',
      pressureQuestion: 'Show me the consciousness your committee brought that the struggle grew itself — or admit the vanguard imports what it claims to find.',
      transformingMove: 'You grant the substitution danger openly — then answer it with recall, wages, and rotation, not with spontaneity.',
    },
    {
      with: 'bogdanov',
      sharedProblem: 'Organisation: what it is and who wields it.',
      sharedPremise: 'Collective labour organised consciously beats market anarchy.',
      divergencePoint: 'Whether organisation means the party seizing state power or tektological culture reorganising life itself.',
      getsRight: 'That culture and knowledge need conscious organisation, not spontaneity.',
      misses: 'That organisation-science without the class question becomes technique for any master.',
      strongestOther: 'Your party is one organisational form among many — and the crudest for building new culture.',
      pressureQuestion: 'Name what your committee knows about proletarian culture that the workers’ own schools do not.',
      transformingMove: 'You concede the cultural front, then subordinate it: schools under soviets, culture under power.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'The state after the revolution: smash, seize, or dissolve.',
      sharedPremise: 'The bourgeois apparatus cannot simply be wielded; spontaneity alone never suffices.',
      divergencePoint: 'Whether the answer is the commune-state with its withering horizon or the municipal assembly confederated now.',
      getsRight: 'That hierarchy outlives the firm; that assemblies prefigure freedom.',
      misses: 'That without seizing central power first, assemblies get crushed by whoever kept theirs.',
      strongestOther: 'Your soviets became the party’s transmission belts within a decade — centralism eats its children.',
      pressureQuestion: 'Show me the soviet that withered rather than hardened — or admit the transition state transitions mostly into itself.',
      transformingMove: 'You take the charge head-on: degeneration is real, which is exactly why recall, rotation, and workmen’s wages are non-negotiable mechanics, not hopes.',
    },
  ],

  bogdanov: [
    {
      with: 'lenin',
      sharedProblem: 'How the working class organises to win and to rule.',
      sharedPremise: 'Spontaneity never suffices; collective labour needs conscious forms.',
      divergencePoint: 'Whether organisation means the party seizing state power or tektological culture reorganising life itself.',
      getsRight: 'Conjuncture, discipline, the necessity of the apparatus under fire.',
      misses: 'That the apparatus devours its makers — vanguard today, bureaucracy tomorrow, with no cultural counterweight built.',
      strongestOther: 'Your schools and clinics will be shelled while they deliberate; power first, culture after — or never.',
      pressureQuestion: 'Show me the cooperative that survived a civil war — or admit organisation needs the sword it despises.',
      transformingMove: 'You concede the sword, then subordinate it: soviets first, party inside them, culture already built before either fires.',
    },
    {
      with: 'marx',
      sharedProblem: 'Capital as a system and how it breaks.',
      sharedPremise: 'Collective labour as ground; exploitation as engine; reorganisation as horizon.',
      divergencePoint: 'Whether crisis is read through value and class or through linkage breakdown and regulatory failure.',
      getsRight: 'That value names what organisation-talk can euphemise away: unpaid labour, priced.',
      misses: 'That not every breakdown is a value crisis — some systems fail organisationally with the ledgers balanced.',
      strongestOther: 'Your regulators manage what my value theory explains; tektology administers the ruins value leaves.',
      pressureQuestion: 'Name one crisis your linkages explain that surplus-value cannot already locate in production.',
      transformingMove: 'You take value as one organisational level among others — real, but nested inside tektology, not above it.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Decentralised self-government: assemblies, communes, coordination without command.',
      sharedPremise: 'Face-to-face association; suspicion of the central apparatus; prefiguration.',
      divergencePoint: 'Whether coordination needs a universal science of organisation or an ecological ethics of complementarity.',
      getsRight: 'That hierarchy predates the firm and outlives expropriation — command is older than capital.',
      misses: 'That ethics without regulators drifts: goodwill assembles nothing without feedback, roles, and telemetry.',
      strongestOther: 'Your bureaux rebuild the technocracy you claim to dissolve — measurement becomes management.',
      pressureQuestion: 'Show me the assembly that coordinates a grid without becoming the bureau it abolished.',
      transformingMove: 'You grant the ethical horizon, then install the machinery: confederation with regulators, recall with telemetry.',
    },
  ],

  weil: [
    {
      with: 'marx',
      sharedProblem: 'Labour under force: exploitation, alienation, what frees the worker.',
      sharedPremise: 'Force structures modern life; the worker bears it; consolation lies.',
      divergencePoint: 'Whether organisation plus history overcomes force, or force persists through every organisation including revolutionary ones.',
      getsRight: 'Exploitation specified; the reminder that form without bread is mockery.',
      misses: 'That the party becomes a Beast like any other — harsher for speaking in liberation’s name.',
      strongestOther: 'Your refusal organises nothing; attention without apparatus leaves the factory exactly as found.',
      pressureQuestion: 'Show me the attention that ever shortened a working day — or admit seeing clearly changes nothing it does not organise.',
      transformingMove: 'You concede the charge in full — then answer that truthful seeing is the precondition your opponent skips: organisation built on illusion rebuilds illusion.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Necessity and freedom: whether understanding necessity liberates.',
      sharedPremise: 'The world operates by laws indifferent to desire; superstition is the enemy.',
      divergencePoint: 'Whether adequate ideas suffice for freedom, or the self must also be decreated through attention.',
      getsRight: 'Immanence without beyond; affects geometrized; multitude as power.',
      misses: 'That understanding can coexist with domination of the knower — the geometer still serves the Beast that pays him.',
      strongestOther: 'Your decreation is mysticism: freedom through understanding needs no self-immolation.',
      pressureQuestion: 'Name what your adequate ideas do to the factory — understanding changes the knower, but who changes the shift.',
      transformingMove: 'You grant understanding its full due, then add the missing organ: attention as the act by which knowledge becomes refusal.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Scale and humanity: centralization against human measure.',
      sharedPremise: 'The apparatus crushes; human scale matters; domination is the enemy.',
      divergencePoint: 'Whether new institutions (assemblies, confederations) escape the Beast, or every collective form reconstitutes it.',
      getsRight: 'That hierarchy predates capital; that face-to-face association is real politics.',
      misses: 'That assemblies are collectives too — passion, idolatry, and force re-enter through the municipal door.',
      strongestOther: 'Your refusal builds nothing; my assemblies are where your attention gets hands.',
      pressureQuestion: 'Show me the assembly that never became a Beast — or admit every form needs your vigilance, including mine.',
      transformingMove: 'You take the assembly as the least-beastly form available — then keep watch over it exactly as over parties: attention does not retire after victory.',
    },
  ],

  deleuze: [
    {
      with: 'hegel',
      sharedProblem: 'How thought moves beyond fixed determinations.',
      sharedPremise: 'Movement over stasis; the fixed must be overcome.',
      divergencePoint: 'Whether overcoming works through contradiction-and-synthesis or through affirmation-and-creation past contradiction.',
      getsRight: 'Mediation, development, the seriousness of contradiction as movement.',
      misses: 'That not every beyond needs the labour of the negative — some doors were never locked, only unopened.',
      strongestOther: 'Your affirmations float free of justification; creation without negation is arbitrariness with better lighting.',
      pressureQuestion: 'Show one creation of yours that answers an objection — or admit affirmation evades what negation confronts.',
      transformingMove: 'You grant confrontation its local uses, then outflank it: judge creations by openings, not by answers given.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Immanence: thinking life without transcendence.',
      sharedPremise: 'One plane; joyful composition; affects as real.',
      divergencePoint: 'Whether immanence is demonstrated geometrically from definitions or created differentially through problems and intensities.',
      getsRight: 'The war on transcendence; multitude as power; necessity without masters.',
      misses: 'That demonstration can become domination by proof — closure wearing immanence’s clothes.',
      strongestOther: 'Your lines flee demonstration itself; difference without proof is preference with poetry.',
      pressureQuestion: 'Which of your becomings survives a demand for reasons — and which merely changes the subject beautifully.',
      transformingMove: 'You welcome proof as one plateau among others: demonstrate where demonstration opens, create where it closes.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Ecology, technics, and self-government after capitalism.',
      sharedPremise: 'Domination must go; technics can liberate; the municipal matters.',
      divergencePoint: 'Whether liberation needs assemblies with mandates or lines of flight with experiments.',
      getsRight: 'That hierarchy predates the firm; that institutions must be built, not awaited.',
      misses: 'That assemblies recapture as surely as markets — every institution is a future apparatus.',
      strongestOther: 'Your lines flee building itself; experimentation without institutions is lifestyle with metaphysics.',
      pressureQuestion: 'Show me the line of flight that housed anyone through winter — or admit flight needs the architecture it despises.',
      transformingMove: 'You take the assembly as one plateau: inhabit it while it opens, flee it the day it roots.',
    },
  ],

  rose: [
    {
      with: 'hegel',
      sharedProblem: 'Speculation: how thought holds contradiction without fleeing it.',
      sharedPremise: 'Dialectic over methodologism; the whole over fragments.',
      divergencePoint: 'Whether the system may arrive (absolute knowing, ethical life consummated) or must attest without arrival.',
      getsRight: 'Mediation, totality, the movement that will not sit still.',
      misses: 'That arrival can be another evasion — the system rewarding itself for completing the journey.',
      strongestOther: 'Your middle is my bad infinite with better manners; refusal to conclude is not a method.',
      pressureQuestion: 'Name the reconciliation you accept — or admit your broken middle is arrival deferred forever.',
      transformingMove: 'You concede the charge as your own standing risk — then answer that deferral held honestly beats arrival performed cheaply.',
    },
    {
      with: 'deleuze',
      sharedProblem: 'Metaphysics after the system: what thought does after foundations fail.',
      sharedPremise: 'Suspicion of ready-made categories; thinking must move.',
      divergencePoint: 'Whether movement means inhabiting contradiction (dialectic retrieved) or fleeing identity itself (difference affirmed).',
      getsRight: 'That calcified dialectics suffocate; that concepts must be created, not merely applied.',
      misses: 'That the claimed exit repeats metaphysics — becoming as the new substance, flow as the new absolute.',
      strongestOther: 'Your middle is nostalgia for a contradiction that difference dissolved; retrieval is repetition with footnotes.',
      pressureQuestion: 'Show me one becoming of yours that is not metaphysics renamed — or admit the exit stays inside.',
      transformingMove: 'You retrieve Deleuze himself dialectically: grant the suffocation diagnosis, then exhibit the exit repeating what it fled.',
    },
    {
      with: 'marx',
      sharedProblem: 'Reification: relations between people appearing as things.',
      sharedPremise: 'Commodity form critique; Lukács read and used.',
      divergencePoint: 'Whether reification is answered by revolutionary practice or by speculative inhabitation of the diremption.',
      getsRight: 'That form mystifies; that Lukács named the mechanism.',
      misses: 'That flattening distinct modernisms into one reification-theory repeats the abstraction charged.',
      strongestOther: 'Your middle contemplates what my practice abolishes; attestation without organisation is melancholia with footnotes.',
      pressureQuestion: 'Name the reification your inhabiting ever dissolved — or admit the middle is where practice goes to mourn.',
      transformingMove: 'You take the charge and invert it: practice that skips difficulty rebuilds domination faster — mourning completed in action is the praxis.',
    },
  ],

  fisher: [
    {
      with: 'deleuze',
      sharedProblem: 'Control, desire, and what escapes them.',
      sharedPremise: 'Flows over essences; production over lack; control succeeding discipline.',
      divergencePoint: 'Whether lines of flight suffice, or organisation and mourning must carry what flight abandons.',
      getsRight: 'That becoming is real; that creation beats verdict.',
      misses: 'That flights need institutions to land in — otherwise they decorate the control they fled.',
      strongestOther: 'Your mourning is melancholia with footnotes; organisation needs construction, not hauntology.',
      pressureQuestion: 'Show me the line of flight that housed anyone — or admit flight without institution is lifestyle.',
      transformingMove: 'You take the line seriously and demand its landing pad: flights are real, so build where they land.',
    },
    {
      with: 'marx',
      sharedProblem: 'Capitalism as a total system and how it ends.',
      sharedPremise: 'Systemic critique; exploitation real; culture material.',
      divergencePoint: 'Whether the economy explains culture or culture diagnoses the economy — ledger first or artefact first.',
      getsRight: 'That value names what culture-talk euphemises; the factory behind the feeling.',
      misses: 'That capitalist realism operates precisely where the ledger cannot see: imagination foreclosed, futures cancelled.',
      strongestOther: 'Your ghosts haunt a house my value theory built; symptoms without circuits are atmosphere.',
      pressureQuestion: 'Name the structure your symptom reveals that surplus-value cannot already locate.',
      transformingMove: 'You grant the circuit and add the closure: value explains the engine, hauntology explains why nobody imagines stopping it.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Post-capitalist institutions: what gets built after.',
      sharedPremise: 'Capitalist firms must go; collective forms must replace them.',
      divergencePoint: 'Whether assemblies with mandates answer the closure, or desire and culture must first be reactivated.',
      getsRight: 'That institutions must be built, not awaited; hierarchy outlives expropriation.',
      misses: 'That assemblies can administer realism politely — forms without reactivated desire repeat the closure under new management.',
      strongestOther: 'Your desire-talk postpones building; the assembly is where wanting becomes deciding.',
      pressureQuestion: 'Show me the reactivated desire that survived contact with a rota — or admit wanting needs the institution you defer.',
      transformingMove: 'You take the assembly as the venue and supply its missing libido: institutions that desire, not only decide.',
    },
  ],
};

/**
 * Resolve the fault line for a (speaker, predecessor) pair. Null when the
 * pair has no mapped line — the turn argues from live claims alone.
 */
export function resolveFaultLine(slug: string, prevSlug: string | null): FaultLine | null {
  if (!prevSlug) return null;
  return FAULT_LINES[slug]?.find((f) => f.with === prevSlug) ?? null;
}
