/**
 * FAULT LINES — central relationship map (Phase 11).
 *
 * Comparisons between thinkers live HERE, not in individual THINKING
 * files: each file carries only its own engine, and this map carries what
 * happens when one machinery meets another. Runtime resolves the pair
 * (speaker, PREV) per turn; the meta view in `docs/thinking-diversity.md`
 * reads the same map to evaluate distinctiveness.
 *
 * Chain per entry: PROBLEM → SHARED PREMISE → DIVERGENCE → DIFFERENT
 * DIAGNOSIS → DIFFERENT OPERATION → DIFFERENT CONSEQUENCE.
 */
import type { FaultLine } from './thinking-types';

export const FAULT_LINES: Record<string, FaultLine[]> = {
  bookchin: [
    {
      with: 'marx',
      sharedProblem: 'Domination and unfreedom produced by capitalism.',
      sharedPremise: 'The present profit system keeps producing top-down control by how it is built, not just by bad behaviour from single owners.',
      divergencePoint: 'Whether the worker-versus-owner clash is the main cause that explains the rest, or one work-shape set inside a wider older system of ranked command.',
      getsRight: 'Exploitation, accumulation, the grow-or-die imperative.',
      misses: 'Patriarchy, gerontocracy, bureaucracy, the state — command that predates and outlives any firm.',
      strongestOther: 'Who does the set-up work and who pockets the gain is what keeps the control going; widen the picture and you lose grip on that daily engine.',
      pressureQuestion: 'Show me a hierarchy your class analysis explains without importing age, gender, office, or state — or admit the frame is wider than the factory.',
      transformingMove: 'You keep the worker-owner finding and set it inside the wider history of ranked command; you still answer in the local citizen meeting that runs daily life — not the single workplace but the town and its linked towns — where use-rights follow need and different groups supply what the other lacks, instead of pay-per-job and trade-for-profit.',
    },
    {
      with: 'bloch',
      sharedProblem: 'How hope becomes material rather than mood.',
      sharedPremise: 'What comes next is not fixed; real chances already present can guide what people do now.',
      divergencePoint: 'Whether hoping needs a built decision-place now (local meetings that link up) or lives first as forward-looking awareness in stories, songs, and day-pictures.',
      getsRight: 'Hope as objective category; alliance technology; the future organising the present.',
      misses: 'The institutional machinery that would stop hope evaporating into culture.',
      strongestOther: 'Without a sense of what is still forming, meetings just run today’s routine; decision-places with no forward look repeat top-down control in polite form.',
      pressureQuestion: 'Where do your citizens learn to hope — and what stops your assembly governing a hopeless present?',
      transformingMove: 'You give hoping a home: the local meeting as the room where forward-looking wants get voted into binding jobs — and schooling as the training that teaches residents to build with their hands, not only to wish.',
    },
    {
      with: 'lenin',
      sharedProblem: 'How the dominated organise to win.',
      sharedPremise: 'Acting on impulse with no lasting shape loses; joint planning is hard work.',
      divergencePoint: 'Whether clear shared purpose must be carried in by a tight central group or grown in local meetings that rule themselves face to face.',
      getsRight: 'Discipline, programme, the refusal of lifestyle politics.',
      misses: 'That substitution — party for class, committee for assembly — rebuilds hierarchy under revolutionary names.',
      strongestOther: 'Without tight central drill the push is smashed; local meetings talk while the central power moves.',
      pressureQuestion: 'Who can recall your organisers, where, and how fast — or is accountability another word for trust?',
      transformingMove: 'You keep the drill and change who holds it: firm rule-bound planning inside the local meeting, with chosen go-betweens bound by orders and removable at once inside linked towns — a second decision-power facing the central power, never a grab of it.',
    },
  ],

  bloch: [
    {
      with: 'marx',
      sharedProblem: 'How the dominated move from suffering the world to changing it.',
      sharedPremise: 'What people do counts more than what they merely think over; the present profit system must be ended, not just run more kindly.',
      divergencePoint: 'Whether today is read first through built-up outer conditions (tools, work set-ups, the dated line-up of groups) or through forward-pulling inner life (bodily need, day-pictures, what is still forming).',
      getsRight: 'The material weight of conditions; the discipline against wishing.',
      misses: 'The subjective surplus — why people move before conditions are ripe, and what moves them.',
      strongestOther: 'Without sober checking of outer conditions, hoping becomes paint over losses; talk of direction with no grip on tools and work set-ups is mere preaching.',
      pressureQuestion: 'Name the tendency that carries your hope — its forces, its conditions, its date — or admit you are preaching to the hungry.',
      transformingMove: 'You keep the sober check of tools and work set-ups and add the forward edge: the same conditions read closely for what new life they may be carrying.',
    },
    {
      with: 'hegel',
      sharedProblem: 'How thought follows a world that will not stand still.',
      sharedPremise: 'Clashing claims move things; what holds true shows in the working-through, not in a still snap-shot.',
      divergencePoint: 'Whether the working-through can finish in full self-knowledge and a closed ring, or stays open at the forward edge where the new forms.',
      getsRight: 'Mediation, determinate negation, the seriousness of contradiction.',
      misses: 'The future as a real dimension — his owl flies at dusk, after the deed.',
      strongestOther: 'A working-through that never finishes is a road with no destination; with no closing there is no knowing, only wishing.',
      pressureQuestion: 'If nothing ever arrives, what distinguishes your Front from endless deferral — show me one Novum that actually happened.',
      transformingMove: 'You point to old promises kept late: past hopes cashed out after long delay — proof that an open road can still reach real arrivals without sealing shut.',
    },
    {
      with: 'kant',
      sharedProblem: 'What reason may hope for, and on what grounds.',
      sharedPremise: 'Hoping needs a clear-headed shape; it cannot be bare feeling.',
      divergencePoint: 'Whether hoping stays a working rule for action inside set bounds, or names how the world itself is — unfinished and still forming.',
      getsRight: 'Dignity, practical reason, the discipline of the postulate.',
      misses: 'That the world itself is unfinished enough to warrant hope as knowledge, not only as duty.',
      strongestOther: 'Turning hoping into world-structure smuggles unchecked claims past the careful border-check.',
      pressureQuestion: 'Is your not-yet known, or only willed — and what tribunal judges the difference?',
      transformingMove: 'Your schooled hoping: hopes that submit to the conditions check, working rules raised into testable guesses with named supports.',
    },
  ],

  spinoza: [
    {
      with: 'hegel',
      sharedProblem: 'How the one and the many hang together without dualism.',
      sharedPremise: 'Your single-whole view is the agreed starting point — the other side itself says thought must first pass through it.',
      divergencePoint: 'Whether the single whole must grow into self-knowing mind through clash and change over time, or stands complete as self-made must-be with no built-in goal.',
      getsRight: 'Mediation, development, the seriousness of contradiction as movement.',
      misses: 'That adding purpose to necessity reintroduces the final causes you struck out.',
      strongestOther: 'A still whole cannot grasp coming-to-be; without set clash-and-carry, new things are mere trim on what had to be.',
      pressureQuestion: 'Show me one becoming your substance generates that your definitions did not already contain — or admit the system describes eternity, not history.',
      transformingMove: 'You allow real shifting among the parts inside what must be; you refuse the verdict that what must be needed finishing.',
    },
    {
      with: 'marx',
      sharedProblem: 'Collective power: how the many compose into force.',
      sharedPremise: 'No outside level, and the many acting together — the other side hand-copied your early politics book; the shared-rule plan runs through both.',
      divergencePoint: 'Whether how people join is read through feelings and cause-grasping thoughts (joining as such) or through dated work set-ups (owner-versus-worker as the shape).',
      getsRight: 'Exploitation specified; history given a material engine rather than a geometric diagram.',
      misses: 'That class struggle is one shape of composing and decomposing powers — specified truly, but not exhaustively.',
      strongestOther: 'Group strengths with no grip on who runs the workplaces float; your many-together joins in thin air where workshops should be.',
      pressureQuestion: 'Which compositions feed whom, under what ownership of the means — answer materially or your geometry administers the given.',
      transformingMove: 'You take the workshop as one feeling-loaded joining among others; you keep the pocketed-unpaid-work finding inside the wider check.',
    },
    {
      with: 'deleuze',
      sharedProblem: 'Immanence and the affects: thinking life without transcendence.',
      sharedPremise: 'One shared world, glad joining, strength to move and be moved.',
      divergencePoint: 'Whether the one-world view is proved step by step from set meanings or built piecemeal through live puzzles, strong points, and fresh comings-to-be.',
      getsRight: 'Carries immanence into multiplicity; hears the larval and intensive where you heard the demonstrated.',
      misses: 'That untying demonstration from creation risks trading necessity for proliferation — many differences, fewer proofs.',
      strongestOther: 'Your set-up proves what it already took for granted; fresh unlikeness makes what your starting rules cannot reach.',
      pressureQuestion: 'Which of your demonstrations produces a single new difference — and which merely re-labels eternity?',
      transformingMove: 'You welcome strong points as single cases under study; you ask for their full causes before praising them.',
    },
  ],

  kant: [
    {
      with: 'hegel',
      sharedProblem: 'How reason knows itself and its limits.',
      sharedPremise: 'Thought must hang together as one ordered whole; bare lived events alone never settle it.',
      divergencePoint: 'Whether the clear head must stop at borders it sets for itself, or every border breeds its own far side through clash.',
      getsRight: 'Mediation, development, the seriousness of contradiction as movement.',
      misses: 'That some bounds are load-bearing, not cowardice — removing them restarts dogmatism under dialectical names.',
      strongestOther: 'Your border-court freezes coming-to-be into lawmaking; borders set as timeless are themselves unchecked.',
      pressureQuestion: 'Show me one bound of yours that is not itself a historical product — or admit the tribunal needs dating.',
      transformingMove: 'You allow real growth its due inside what shows up for us, and hold the line at knowing-claims about the whole: coming-to-be is real, all-condition-free knowing is not.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Whether reason can form a complete system without illusion.',
      sharedPremise: 'One hung-together must-be is the bar; loose bits are failure.',
      divergencePoint: 'Whether what must be is proved from the single whole or checked through what knowing itself needs first.',
      getsRight: 'Immanence, the critique of superstition, freedom as understood necessity.',
      misses: 'That deduction without a prior audit of entitlement proves only what its definitions smuggled in.',
      strongestOther: 'Your borders are fear dressed as checking; what is proved to must-be needs no leave.',
      pressureQuestion: 'Demonstrate one substance without assuming it — or admit your geometry begs its first question.',
      transformingMove: 'You keep the one-whole aim and put it to the by-what-right test: oneness must be earned through checking, never taken for granted in a starting meaning.',
    },
    {
      with: 'marx',
      sharedProblem: 'What emancipation requires: rightful form or material conditions.',
      sharedPremise: 'People as makers of their own purpose; top-down control as the foe.',
      divergencePoint: 'Whether fair rules on paper are enough once voted, or being free waits on bread-and-time supports no law makes by itself.',
      getsRight: 'Exploitation specified; the reminder that form without bread is mockery.',
      misses: 'That abandoning form for outcome rebuilds domination under efficiency’s name.',
      strongestOther: 'Your fair-rules talk is an owner-class shape; worth with no bread-and-time behind it is a pretty sentence.',
      pressureQuestion: 'Name one right of yours that feeds anyone — or admit the tribunal needs a kitchen.',
      transformingMove: 'You grant the kitchen and keep the border-court: bread-and-time supports make possible what only fair form can back as right.',
    },
  ],

  hegel: [
    {
      with: 'marx',
      sharedProblem: 'How the social whole moves and what drives it.',
      sharedPremise: 'Growth from inside through clash; the rich whole rebuilt from its many sides.',
      divergencePoint: 'Whether the driver is the shared thought working itself out or daily work set-ups shaping shared awareness.',
      getsRight: 'Mediation, totality, the seriousness of contradiction.',
      misses: 'That matter without the concept’s self-movement is just as abstract as the idealism charged — mechanism in material dress.',
      strongestOther: 'Your shared mind is profit-thinking about itself; growth with no work set-up behind it is mere preaching.',
      pressureQuestion: 'Name the productive relations your necessity runs on — or admit the Absolute has no economy.',
      transformingMove: 'You grant the hands-on filling while holding that its shape is thought’s own work: making is real, and its make-sense order is shared thought proving itself.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Whether reason forms one complete system.',
      sharedPremise: 'One hung-together must-be; against loose bits and fear-stories.',
      divergencePoint: 'Whether the single whole finishes itself as self-made must-be or must grow into self-knowing mind through clash and change over time.',
      getsRight: 'Immanence without beyond; affects without moralism; the democratic blueprint.',
      misses: 'That a substance which never becomes cannot think novelty — eternity without biography.',
      strongestOther: 'Your coming-to-be adds nothing but story to what had-to-be already holds.',
      pressureQuestion: 'Show one novelty your system generates that your beginning did not already contain.',
      transformingMove: 'You take the single whole as the true start — and show that starts prove themselves only at the finish.',
    },
    {
      with: 'kant',
      sharedProblem: 'What reason may claim and where it must halt.',
      sharedPremise: 'Tight hung-together order; borders against runaway feeling.',
      divergencePoint: 'Whether borders are voted walls or passing stages that breed their own far side.',
      getsRight: 'Discipline against dogmatism; the tribunal’s honest labour.',
      misses: 'That legislated bounds freeze becoming — critique guarding the status quo of thought.',
      strongestOther: 'Your working-through smuggles unchecked beyond-claims past the border-court you claim to keep.',
      pressureQuestion: 'Derive one bound of yours without presupposing the movement it forbids.',
      transformingMove: 'You keep every border from the other side as a real passing stage — then show it lifting-and-carrying itself forward the moment it is thought.',
    },
  ],

  marx: [
    {
      with: 'hegel',
      sharedProblem: 'How the social whole moves through contradiction.',
      sharedPremise: 'Growth from inside; set rejection that keeps what was true; the rich whole rebuilt from its many sides.',
      divergencePoint: 'Whether the driver is the shared thought working itself out or daily work set-ups shaping shared awareness.',
      getsRight: 'Mediation, totality, the seriousness of contradiction.',
      misses: 'That spirit without production-relations floats — development needs an economy to run on.',
      strongestOther: 'Your hands-on stuff is beyond-talk with workshops; without shared thought working through, work-talk is mere clockwork.',
      pressureQuestion: 'Show one transformation your relations explain that your categories did not already contain.',
      transformingMove: 'You keep the clash-and-carry shape and fill it with hands-on life: every move from the other side re-dated, re-placed in daily making.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Domination and what abolishes it.',
      sharedPremise: 'The present profit system keeps remaking top-down control by structure; pocketed unpaid work is real and central.',
      divergencePoint: 'Whether the worker-owner clash uses up the whole of top-down control or sits inside an older wider ranked command.',
      getsRight: 'That command predates the firm — patriarchy, gerontocracy, bureaucracy are real dominations.',
      misses: 'That without class analysis, hierarchy-talk floats above the relations reproducing it daily.',
      strongestOther: 'Worker-owner rank is one top-down shape among many; your workshop explains the office but not the home.',
      pressureQuestion: 'Name the hierarchy your municipalism abolishes that my class analysis cannot already locate in production.',
      transformingMove: 'You take ranked command as real while holding that pocketed unpaid work stays the daily driver — widen the family tree, keep the workshop.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Collective power and freedom without transcendence.',
      sharedPremise: 'No outside level; being free as a shared strength to act; fear-stories as the foe.',
      divergencePoint: 'Whether how people join is read proof-wise through feelings or time-wise through dated work set-ups.',
      getsRight: 'That inadequate ideas rule through fear; that multitude is the real sovereign.',
      misses: 'That affects without an economy float — joy needs wages, time, and bread.',
      strongestOther: 'Your time-story is proof-shapes with dates; shown must-be is not made must-be.',
      pressureQuestion: 'Which compositions feed whom under what ownership — answer materially or your multitude starves elegantly.',
      transformingMove: 'You take the many-together as the worker-group in the making: feelings real, but lined up for shared action — or nothing.',
    },
  ],

  lenin: [
    {
      with: 'marx',
      sharedProblem: 'How the working class takes power.',
      sharedPremise: 'Worker-owner fight; the central power as owner-rule; joint planning as must.',
      divergencePoint: 'Whether the account waits on outer readiness or lines up that readiness itself through the tight group, the shared news-sheet, and the workers councils.',
      getsRight: 'The materialist foundation; exploitation specified; the Commune as form.',
      misses: 'That spontaneity never delivers consciousness — the movement needs bringing what it cannot grow.',
      strongestOther: 'Your tight group puts itself in place of the workers; the machine built for winning keeps ruling after it.',
      pressureQuestion: 'Show me the consciousness your committee brought that the struggle grew itself — or admit the vanguard imports what it claims to find.',
      transformingMove: 'You grant the swap-in danger openly — then answer it with instant recall, worker-level pay, and regular turnover of posts, not with acting on impulse.',
    },
    {
      with: 'bogdanov',
      sharedProblem: 'Organisation: what it is and who wields it.',
      sharedPremise: 'Joint work planned with open eyes beats blind buying-and-selling.',
      divergencePoint: 'Whether joint planning means the tight group grabbing central power or shared learning reshaping daily life itself.',
      getsRight: 'That culture and knowledge need conscious organisation, not spontaneity.',
      misses: 'That organisation-science without the class question becomes technique for any master.',
      strongestOther: 'Your tight group is one joining-shape among many — and the roughest for growing new shared learning.',
      pressureQuestion: 'Name what your committee knows about proletarian culture that the workers’ own schools do not.',
      transformingMove: 'You grant the learning task, then set it under decision-power: schools under workers councils, shared learning under shared rule.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'The state after the revolution: smash, seize, or dissolve.',
      sharedPremise: 'The owner-run machine cannot simply be picked up and used; acting on impulse alone never suffices.',
      divergencePoint: 'Whether the answer is the workers-commune power that aims to fade away or linked local citizen meetings built now.',
      getsRight: 'That hierarchy outlives the firm; that assemblies prefigure freedom.',
      misses: 'That without seizing central power first, assemblies get crushed by whoever kept theirs.',
      strongestOther: 'Your workers councils turned into the tight group’s errand-belts within ten years — rule-from-centre eats its own young.',
      pressureQuestion: 'Show me the soviet that withered rather than hardened — or admit the transition state transitions mostly into itself.',
      transformingMove: 'You meet the charge head-on: going-bad is real, which is why instant recall, regular turnover, and worker-level pay are fixed mechanics, not wishes.',
    },
  ],

  bogdanov: [
    {
      with: 'lenin',
      sharedProblem: 'How the working class organises to win and to rule.',
      sharedPremise: 'Acting on impulse never suffices; joint work needs shapes made with open eyes.',
      divergencePoint: 'Whether joint planning means the tight group grabbing central power or shared learning reshaping daily life itself.',
      getsRight: 'Conjuncture, discipline, the necessity of the apparatus under fire.',
      misses: 'That the apparatus devours its makers — vanguard today, bureaucracy tomorrow, with no cultural counterweight built.',
      strongestOther: 'Your schools and care-houses will be shelled while they talk; rule first, learning after — or never.',
      pressureQuestion: 'Show me the cooperative that survived a civil war — or admit organisation needs the sword it despises.',
      transformingMove: 'You grant the armed fight, then set it under: workers councils first, the tight group inside them, shared learning already built before either shoots.',
    },
    {
      with: 'marx',
      sharedProblem: 'Capital as a system and how it breaks.',
      sharedPremise: 'Joint work as ground; pocketed unpaid work as driver; re-joining as the far aim.',
      divergencePoint: 'Whether breakdowns are read through priced unpaid work and worker-owner clash or through ties snapping and steering going wrong.',
      getsRight: 'That value names what organisation-talk can euphemise away: unpaid labour, priced.',
      misses: 'That not every breakdown is a value crisis — some systems fail organisationally with the ledgers balanced.',
      strongestOther: 'Your steering-tools manage what my price-and-unpaid-work account explains; your joining-study runs the wreck the price leaves.',
      pressureQuestion: 'Name one crisis your linkages explain that surplus-value cannot already locate in production.',
      transformingMove: 'You take priced work as one joining-level among others — real, but set inside the wider study of how parts hold, not above it.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Decentralised self-government: assemblies, communes, coordination without command.',
      sharedPremise: 'Small-group joining face to face; wariness of the central machine; living now the shape you want later.',
      divergencePoint: 'Whether lining-up needs one shared study of how parts hold or a nature-minded common code where different groups supply what the other lacks.',
      getsRight: 'That hierarchy predates the firm and outlives expropriation — command is older than capital.',
      misses: 'That ethics without regulators drifts: goodwill assembles nothing without feedback, roles, and telemetry.',
      strongestOther: 'Your offices rebuild the expert-rule you claim to end — counting turns into commanding.',
      pressureQuestion: 'Show me the assembly that coordinates a grid without becoming the bureau it abolished.',
      transformingMove: 'You grant the shared-code far aim, then fit the works: linked towns with steering-tools, removable delegates with fast feedback reports.',
    },
  ],

  weil: [
    {
      with: 'marx',
      sharedProblem: 'Labour under force: exploitation, alienation, what frees the worker.',
      sharedPremise: 'Push-and-crush shapes present life; the worker carries it; comfort-stories lie.',
      divergencePoint: 'Whether joint planning plus time overcomes crush, or crush lasts through every joining including overthrow ones.',
      getsRight: 'Exploitation specified; the reminder that form without bread is mockery.',
      misses: 'That the party becomes a Beast like any other — harsher for speaking in liberation’s name.',
      strongestOther: 'Your no builds nothing; careful noticing with no working machine leaves the workshop exactly as found.',
      pressureQuestion: 'Show me the attention that ever shortened a working day — or admit seeing clearly changes nothing it does not organise.',
      transformingMove: 'You grant the charge in full — then answer that truth-seeing comes first where the other side skips it: joint plans built on false pictures rebuild false pictures.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Necessity and freedom: whether understanding necessity liberates.',
      sharedPremise: 'The world runs by rules careless of wishing; fear-stories are the foe.',
      divergencePoint: 'Whether cause-grasping thoughts are enough to free, or the self must also step back through steady full notice.',
      getsRight: 'Immanence without beyond; affects geometrized; multitude as power.',
      misses: 'That understanding can coexist with domination of the knower — the geometer still serves the Beast that pays him.',
      strongestOther: 'Your self-stepping-back is other-world talk: being free through grasping causes needs no self-burning.',
      pressureQuestion: 'Name what your adequate ideas do to the factory — understanding changes the knower, but who changes the shift.',
      transformingMove: 'You grant grasping causes its full due, then add the missing deed: steady full notice as the act by which knowing turns into no.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Scale and humanity: centralization against human measure.',
      sharedPremise: 'The big machine crushes; people-sized measure matters; top-down control is the foe.',
      divergencePoint: 'Whether new decision-places (local meetings, linked towns) get free of the large lump, or every joint shape rebuilds it.',
      getsRight: 'That hierarchy predates capital; that face-to-face association is real politics.',
      misses: 'That assemblies are collectives too — passion, idolatry, and force re-enter through the municipal door.',
      strongestOther: 'Your no builds nothing; my local meetings are where your careful notice gets hands.',
      pressureQuestion: 'Show me the assembly that never became a Beast — or admit every form needs your vigilance, including mine.',
      transformingMove: 'You take the local meeting as the least lump-like shape on offer — then keep watch over it just as over tight groups: careful notice does not clock off after winning.',
    },
  ],

  deleuze: [
    {
      with: 'hegel',
      sharedProblem: 'How thought moves beyond fixed determinations.',
      sharedPremise: 'Going over standing; what is stuck must be got past.',
      divergencePoint: 'Whether getting-past works through clash-and-combine or through yes-saying and fresh making that leaves clash behind.',
      getsRight: 'Mediation, development, the seriousness of contradiction as movement.',
      misses: 'That not every beyond needs the labour of the negative — some doors were never locked, only unopened.',
      strongestOther: 'Your yes-sayings float free of backing; fresh making with no set no is mere whim with better lighting.',
      pressureQuestion: 'Show one creation of yours that answers an objection — or admit affirmation evades what negation confronts.',
      transformingMove: 'You grant head-on clash its local uses, then move round it: judge fresh makes by paths they open, not by replies they give.',
    },
    {
      with: 'spinoza',
      sharedProblem: 'Immanence: thinking life without transcendence.',
      sharedPremise: 'One shared level; glad joining; feelings as real.',
      divergencePoint: 'Whether the one-level view is proved step by step from set meanings or pieced out through live puzzles and strong points.',
      getsRight: 'The war on transcendence; multitude as power; necessity without masters.',
      misses: 'That demonstration can become domination by proof — closure wearing immanence’s clothes.',
      strongestOther: 'Your break-out paths flee proof itself; unlikeness with no reasons is taste with pretty words.',
      pressureQuestion: 'Which of your becomings survives a demand for reasons — and which merely changes the subject beautifully.',
      transformingMove: 'You welcome proof as one flat stretch among others: prove where proving opens, make anew where it shuts.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Ecology, technics, and self-government after capitalism.',
      sharedPremise: 'Top-down control must go; tools can free; the town-level matters.',
      divergencePoint: 'Whether getting free needs local meetings with binding orders or break-out paths with trials.',
      getsRight: 'That hierarchy predates the firm; that institutions must be built, not awaited.',
      misses: 'That assemblies recapture as surely as markets — every institution is a future apparatus.',
      strongestOther: 'Your break-out paths flee building itself; trials with no lasting decision-places are life-style with beyond-talk.',
      pressureQuestion: 'Show me the line of flight that housed anyone through winter — or admit flight needs the architecture it despises.',
      transformingMove: 'You take the local meeting as one flat stretch: live in it while it opens, leave it the day it hardens.',
    },
  ],

  rose: [
    {
      with: 'hegel',
      sharedProblem: 'Speculation: how thought holds contradiction without fleeing it.',
      sharedPremise: 'Working-through-clash over fixed how-to lists; the full shared life over loose bits.',
      divergencePoint: 'Whether the ordered whole may reach home (full self-knowledge, shared life made whole) or must stand by its claim with no homecoming.',
      getsRight: 'Mediation, totality, the movement that will not sit still.',
      misses: 'That arrival can be another evasion — the system rewarding itself for completing the journey.',
      strongestOther: 'Your held middle is my endless line with better manners; refusal to close is not a way.',
      pressureQuestion: 'Name the reconciliation you accept — or admit your broken middle is arrival deferred forever.',
      transformingMove: 'You grant the charge as your own standing risk — then answer that waiting held honestly beats a homecoming acted cheaply.',
    },
    {
      with: 'deleuze',
      sharedProblem: 'Metaphysics after the system: what thought does after foundations fail.',
      sharedPremise: 'Distrust of off-the-shelf boxes; thought must go.',
      divergencePoint: 'Whether going means staying inside the clash (clash-work picked up again) or running from fixed sameness itself (unlikeness yes-said).',
      getsRight: 'That calcified dialectics suffocate; that concepts must be created, not merely applied.',
      misses: 'That the claimed exit repeats metaphysics — becoming as the new substance, flow as the new absolute.',
      strongestOther: 'Your held middle misses a clash that unlikeness melted; picking-up-again is repeating with footnotes.',
      pressureQuestion: 'Show me one becoming of yours that is not metaphysics renamed — or admit the exit stays inside.',
      transformingMove: 'You meet the other side on its own clash-ground: grant the choking verdict, then show the break-out repeating what it fled.',
    },
    {
      with: 'marx',
      sharedProblem: 'Reification: relations between people appearing as things.',
      sharedPremise: 'Criticism of the price-shape; the thing-mask account read and used.',
      divergencePoint: 'Whether people-relations wearing thing-masks are answered by overthrow action or by hard staying-inside the shared split.',
      getsRight: 'That form mystifies; that Lukács named the mechanism.',
      misses: 'That flattening distinct modernisms into one reification-theory repeats the abstraction charged.',
      strongestOther: 'Your held middle looks over what my doing ends; standing-by with no joint plan is stuck grief with footnotes.',
      pressureQuestion: 'Name the reification your inhabiting ever dissolved — or admit the middle is where practice goes to mourn.',
      transformingMove: 'You take the charge and turn it: doing that skips hardness rebuilds top-down control faster — grief finished off in shared work is the real doing.',
    },
  ],

  fisher: [
    {
      with: 'deleuze',
      sharedProblem: 'Control, desire, and what escapes them.',
      sharedPremise: 'Streams over fixed natures; making over missing; bending rule after the drill-hall.',
      divergencePoint: 'Whether break-out paths are enough, or joint plans and grief-work must carry what breaking-out drops.',
      getsRight: 'That becoming is real; that creation beats verdict.',
      misses: 'That flights need institutions to land in — otherwise they decorate the control they fled.',
      strongestOther: 'Your grief-work is stuck gloom with footnotes; joint plans need building, not cancelled-tomorrow ghosts.',
      pressureQuestion: 'Show me the line of flight that housed anyone — or admit flight without institution is lifestyle.',
      transformingMove: 'You take the break-out path seriously and ask for its landing pad: break-outs are real, so build where they touch down.',
    },
    {
      with: 'marx',
      sharedProblem: 'Capitalism as a total system and how it ends.',
      sharedPremise: 'Whole-set-up criticism; pocketed unpaid work real; songs and screens carry weight.',
      divergencePoint: 'Whether the work-and-profit set-up explains songs and screens or songs and screens read the set-up — count-books first or made-things first.',
      getsRight: 'That value names what culture-talk euphemises; the factory behind the feeling.',
      misses: 'That capitalist realism operates precisely where the ledger cannot see: imagination foreclosed, futures cancelled.',
      strongestOther: 'Your cancelled-tomorrow ghosts walk a house my price-and-unpaid-work account built; signs with no cash-loops are mere mood.',
      pressureQuestion: 'Name the structure your symptom reveals that surplus-value cannot already locate.',
      transformingMove: 'You grant the cash-loop and add the shut-in feel: price explains the engine, cancelled-tomorrow ghosts explain why nobody pictures stopping it.',
    },
    {
      with: 'bookchin',
      sharedProblem: 'Post-capitalist institutions: what gets built after.',
      sharedPremise: 'Profit-run firms must go; shared shapes must take their place.',
      divergencePoint: 'Whether local meetings with binding orders answer the shut-in feel, or wanting and shared making must first be woken up.',
      getsRight: 'That institutions must be built, not awaited; hierarchy outlives expropriation.',
      misses: 'That assemblies can administer realism politely — forms without reactivated desire repeat the closure under new management.',
      strongestOther: 'Your wanting-talk puts off building; the local meeting is where wanting turns into deciding.',
      pressureQuestion: 'Show me the reactivated desire that survived contact with a rota — or admit wanting needs the institution you defer.',
      transformingMove: 'You take the local meeting as the hall and bring its missing wanting: decision-places that want, not only vote.',
    },
  ],
};

/**
 * Resolve the fault line for a (speaker, predecessor) pair. Null when the
 * pair has no mapped line — the turn argues from live claims alone.
 */
export function resolveFaultLine(slug: string, prevSlug: string | null): FaultLine | null {
  if (!prevSlug) return null;
  return FAULT_LINES[slug]?.find((f) => f.with === prevSlug) ?? null;
}
