#!/usr/bin/env node
/**
 * Influence grid exporter: CABINET_DEBTS → docs/influence-grid.md.
 *   node scripts/influence-grid.mjs
 *
 * influences.ts stays the single source of truth (heirs derive from debts);
 * this grid is a generated reading view for row-by-row auditing — do not
 * hand-edit the markdown, re-run this script. Fails loudly if a debt points
 * at an unknown slug so the grid can never silently drift.
 */
import { writeFileSync } from 'node:fs';
import { CABINET_DEBTS } from '../src/philosophers/influences.ts';

// Chronological seat order (matches DEFAULT_SEATING_ORDER).
const ORDER = [
  'spinoza', 'kant', 'hegel', 'marx', 'lenin', 'bogdanov',
  'bloch', 'weil', 'bookchin', 'deleuze', 'fisher',
];
const NAME = {
  spinoza: 'Spinoza', kant: 'Kant', hegel: 'Hegel', marx: 'Marx',
  lenin: 'Lenin', bogdanov: 'Bogdanov', bloch: 'Bloch', weil: 'Weil',
  bookchin: 'Bookchin', deleuze: 'Deleuze', fisher: 'Fisher',
};

const known = new Set(ORDER);
for (const [from, debts] of Object.entries(CABINET_DEBTS)) {
  if (!known.has(from)) throw new Error(`unknown debtor slug: ${from}`);
  for (const d of debts) {
    if (!known.has(d.to)) throw new Error(`unknown creditor slug: ${d.to} (from ${from})`);
    if (d.kind !== 'direct' && d.kind !== 'indirect') throw new Error(`bad kind: ${d.kind} (${from}→${d.to})`);
  }
}

// Cell (row debtor, column creditor): D+/D-/D and I+/I-/I combine kind and
// stance; N = no evidenced link; — = self.
// Reading a ROW shows what the seat owes; reading a COLUMN shows who owes it.
const code = (kind, stance) => {
  const base = kind === 'direct' ? 'D' : 'I';
  if (stance === 'positive') return `${base}+`;
  if (stance === 'critical') return `${base}-`;
  return base;
};
const cell = (from, to) => {
  if (from === to) return '—';
  const debt = (CABINET_DEBTS[from] ?? []).find((d) => d.to === to);
  if (!debt) return 'N';
  if (debt.kind !== 'direct' && debt.kind !== 'indirect') throw new Error(`bad kind: ${debt.kind} (${from}→${debt.to})`);
  if (!['positive', 'critical', 'ambivalent'].includes(debt.stance)) throw new Error(`bad stance: ${debt.stance} (${from}→${debt.to})`);
  return code(debt.kind, debt.stance);
};

const head = `| debtor ↓ / creditor → | ${ORDER.map((s) => NAME[s]).join(' | ')} |`;
const rule = `| --- | ${ORDER.map(() => '---').join(' | ')} |`;
const rows = ORDER.map(
  (from) => `| **${NAME[from]}** | ${ORDER.map((to) => cell(from, to)).join(' | ')} |`,
);

const counts = ORDER.map((s) => {
  const out = (CABINET_DEBTS[s] ?? []).length;
  const inn = ORDER.filter((f) => (CABINET_DEBTS[f] ?? []).some((d) => d.to === s)).length;
  return `| **${NAME[s]}** | ${out} | ${inn} | ${out + inn} |`;
});

const md = `# Influence grid (generated)

Do not hand-edit — generated by \`node scripts/influence-grid.mjs\` from
\`src/philosophers/influences.ts\` (the single source of truth). Re-run after
any debt change.

D = direct (read closely and answered, criticism and ruptures count) ·
I = indirect (through intermediaries or the wider tradition) ·
+ embraces and carries forward · − attacks or breaks · bare is mixed ·
N = no evidenced link (cannot currently demonstrate — not "unrelated") ·
— = self.

${head}
${rule}
${rows.join('\n')}

## Degree (debts out / heirs in / total)

| seat | owes | owed by | total |
| --- | --- | --- | --- |
${counts.join('\n')}
`;

writeFileSync(new URL('../docs/influence-grid.md', import.meta.url), md);
console.log(`wrote docs/influence-grid.md (${ORDER.length}x${ORDER.length})`);
